name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore api/FrozenLand.PlaneParking.API/FrozenLand.PlaneParking.API.sln
    - name: Build
      run: dotnet build --no-restore api/FrozenLand.PlaneParking.API/FrozenLand.PlaneParking.API.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal api/FrozenLand.PlaneParkingAssistant.Core.Tests/FrozenLand.PlaneParkingAssistant.Core.Tests.csproj
