name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: api/FrozenLand.PlaneParking.API
      run: dotnet restore FrozenLand.PlaneParking.API.sln
    - name: Build
      working-directory: api/FrozenLand.PlaneParking.API
      run: dotnet build --no-restore
    - name: Test
      working-directory: api/FrozenLand.PlaneParking.Core.Tests
      run: dotnet test --no-build --verbosity normal
